#pragma once

//          PADMOD - alternate pin functions

#define HIICE_OFS   (7) /** offset of HIICE bit */
#define IICE_OFS    (6) /** offset of IICE bit */
#define HVE_OFS     (5) /** offset of HVE bit */
#define HclpE_OFS   (4) /** offset of HclpE bit */
#define FclkE_OFS   (1) /** offset of FclkE bit */
#define P26E_OFS    (0) /** offset of P26E bit */

#define HIICE   (1 << HIICE_OFS)    /** Write 1 to enable HIIC on P3.0/1 (GPIO or UART otherwise) */
#define IICE    (1 << IICE_OFS)     /** Write 1 to enable IIC on P6.0/1  (GPIO otherwise) */
#define HVE     (1 << HVE_OFS)      
#define HclpE   (1 << HclpE_OFS)
#define FclkE   (1 << FclkE_OFS)
#define P26E    (1 << P26E_OFS)

#define DA3E_OFS (7)
#define DA2E_OFS (6)
#define DA1E_OFS (5)
#define DA0E_OFS (4)
#define AD3E_OFS (3)
#define AD2E_OFS (2)
#define AD1E_OFS (1)
#define AD0E_OFS (0)

#define DA3E (1 << DA3E_OFS)
#define DA2E (1 << DA2E_OFS)
#define DA1E (1 << DA1E_OFS)
#define DA0E (1 << DA0E_OFS)
#define AD3E (1 << AD3E_OFS)
#define AD2E (1 << AD2E_OFS)
#define AD1E (1 << AD1E_OFS)
#define AD0E (1 << AD0E_OFS)


/* Offsets are not defined for pin output enable, since they follow natural order */
#define P47oe (1 << 7)
#define P46oe (1 << 6)
#define P45oe (1 << 5)
#define P44oe (1 << 4)
#define P43oe (1 << 3)
#define P42oe (1 << 2)
#define P41oe (1 << 1)
#define P40oe (1 << 0)

#define P57oe (1 << 7)
#define P56oe (1 << 6)
#define P55oe (1 << 5)
#define P54oe (1 << 4)
#define P53oe (1 << 3)
#define P52oe (1 << 2)
#define P51oe (1 << 1)
#define P50oe (1 << 0)

//          OPTION
#define PWMF_OFS    (7)
#define DIV253_OFS  (6)
#define SlvAvs1_OFS (5)
#define SlvAbs0_OFS (4)
#define ENSCL_OFS   (3)
#define Msel_OFS    (2)
#define MIICF1_OFS  (1)
#define MIICF0_OFS  (0)

#define PWMF    (1 << PWMF_OFS)
#define DIV253  (1 << DIV253_OFS)
#define SlvAvs1 (1 << SlvAvs1_OFS)
#define SlvAbs0 (1 << SlvAbs0_OFS)
#define ENSCL   (1 << ENSCL_OFS)
#define Msel    (1 << Msel_OFS)
#define MIICF1  (1 << MIICF1_OFS)
#define MIICF0  (1 << MIICF0_OFS)

#define P40 (1 << 0)
#define P41 (1 << 0)
#define P42 (1 << 0)
#define P43 (1 << 0)
#define P44 (1 << 0)
#define P45 (1 << 0)
#define P46 (1 << 0)
#define P47 (1 << 0)

#define P50 (1 << 0)
#define P51 (1 << 0)
#define P52 (1 << 0)
#define P53 (1 << 0)
#define P54 (1 << 0)
#define P55 (1 << 0)
#define P56 (1 << 0)
#define P57 (1 << 0)

#define P60 (1 << 0)
#define P61 (1 << 0)
#define P62 (1 << 0)

#define CVpre_OFS   (7)
#define Hpol_OFS    (5)
#define Vpol_OFS    (4)
#define Hpre_OFS    (3)
#define Vpre_OFS    (2)
#define Hoff_OFS    (1)
#define Voff_OFS    (0)

#define CVpre   (1 << CVpre_OFS)
#define Hpol    (1 << Hpol_OFS)
#define Vpol    (1 << Vpol_OFS)
#define Hpre    (1 << Hpre_OFS)
#define Vpre    (1 << Vpre_OFS)
#define Hoff    (1 << Hoff_OFS)
#define Voff    (1 << Voff_OFS)


#define Hovf_OFS    (7)
#define HF13_OFS    (5)
#define HF12_OFS    (4)
#define HF11_OFS    (3)
#define HF10_OFS    (2)
#define HF9_OFS     (1)
#define HF8_OFS     (0)
#define HF7_OFS     (7)
#define HF6_OFS     (6)
#define HF5_OFS     (5)
#define HF4_OFS     (4)
#define HF3_OFS     (3)
#define HF2_OFS     (2)
#define HF1_OFS     (1)
#define HF0_OFS     (0)

#define Hovf    (1 << Hovf_OFS)
#define HF13    (1 << HF13_OFS)
#define HF12    (1 << HF12_OFS)
#define HF11    (1 << HF11_OFS)
#define HF10    (1 << HF10_OFS)
#define HF9     (1 << HF9_OFS)
#define HF8     (1 << HF8_OFS)
#define HF7     (1 << HF7_OFS)
#define HF6     (1 << HF6_OFS)
#define HF5     (1 << HF5_OFS)
#define HF4     (1 << HF4_OFS)
#define HF3     (1 << HF3_OFS)
#define HF2     (1 << HF2_OFS)
#define HF1     (1 << HF1_OFS)
#define HF0     (1 << HF0_OFS)

#define Vovf_OFS    (7)
#define VF11_OFS    (3)
#define VF10_OFS    (2)
#define VF9_OFS     (1)
#define VF8_OFS     (0)
#define VF7_OFS     (7)
#define VF6_OFS     (6)
#define VF5_OFS     (5)
#define VF4_OFS     (4)
#define VF3_OFS     (3)
#define VF2_OFS     (2)
#define VF1_OFS     (1)
#define VF0_OFS     (0)

#define Vovf    (1 << Vovf_OFS)
#define VF11    (1 << VF11_OFS)
#define VF10    (1 << VF10_OFS)
#define VF9     (1 << VF9_OFS)
#define VF8     (1 << VF8_OFS)
#define VF7     (1 << VF7_OFS)
#define VF6     (1 << VF6_OFS)
#define VF5     (1 << VF5_OFS)
#define VF4     (1 << VF4_OFS)
#define VF3     (1 << VF3_OFS)
#define VF2     (1 << VF2_OFS)
#define VF1     (1 << VF1_OFS)
#define VF0     (1 << VF0_OFS)

#define C1_OFS      (7)
#define C0_OFS      (6)
#define NoHins_OFS  (5)
#define VBpl_OFS    (0)
#define HBpl_OFS    (1)

#define C1      (1 << C1_OFS)
#define C0      (1 << C0_OFS)
#define NoHins  (1 << NoHins_OFS)
#define HBpl    (1 << VBpl_OFS  )
#define VBpl    (1 << HBpl_OFS  )

#define CLPEG_OFS (6)
#define CLPPO_OFS (5)
#define CLPW2_OFS (4)
#define CLPW1_OFS (3)
#define CLPW0_OFS (2)

#define CLPEG (1 << CLPEG_OFS)
#define CLPPO (1 << CLPPO_OFS)
#define CLPW2 (1 << CLPW2_OFS)
#define CLPW1 (1 << CLPW1_OFS)
#define CLPW0 (1 << CLPW0_OFS)

#define HPRchg_OFS  (7)
#define VPRchg_OFS  (6)
#define HPLchg_OFS  (5)
#define VPLchg_OFS  (4)
#define Hchg_OFS    (3)
#define VFchg_OFS   (2)
#define Vsync_OFS   (0)

#define HPRchg  (1 << HPRchg_OFS)
#define VPRchg  (1 << VPRchg_OFS)
#define HPLchg  (1 << HPLchg_OFS)
#define VPLchg  (1 << VPLchg_OFS)
#define Hchg    (1 << Hchg_OFS)
#define VFchg   (1 << VFchg_OFS)
#define Vsync   (1 << Vsync_OFS)


#define EHPR_OFS    (7)
#define EVPR_OFS    (6)
#define EHPL_OFS    (5)
#define EVPL_OFS    (4)
#define EHF_OFS     (3)
#define EVF_OFS     (2)
#define Evsync_OFS  (0)

#define EHPR    (1 << EHPR_OFS)
#define EVPR    (1 << EVPR_OFS)
#define EHPL    (1 << EHPL_OFS)
#define EVPL    (1 << EVPL_OFS)
#define EHF     (1 << EHF_OFS)
#define EVF     (1 << EVF_OFS)
#define Evsync  (1 << Evsync_OFS)

#define MackO (1 << 2)
#define P     (1 << 1)
#define S     (1 << 0)

#define WadrB_OFS       (7)
#define WadrA_OFS       (6)
#define SlvRWB_OFS      (5)
#define SackIn_OFS      (4)
#define SLVS_OFS        (3)
#define SlvAlsb1_OFS    (1)
#define SlvAlsb0_OFS    (0)
#define MAckIn_OFS      (7)

#define WadrB       (1 << WadrB_OFS)
#define WadrA       (1 << WadrA_OFS)
#define SlvRWB      (1 << SlvRWB_OFS)
#define SackIn      (1 << SackIn_OFS)
#define SLVS        (1 << SLVS_OFS)
#define SlvAlsb1    (1 << SlvAlsb1_OFS)
#define SlvAlsb0    (1 << SlvAlsb0_OFS)
#define MAckIn      (1 << MAckIn_OFS)

#define TXBI_OFS    (7)
#define RCBI_OFS    (6)
#define SlvBMI_OFS  (5)
#define TXAI_OFS    (4)
#define RCAI_OFS    (3)
#define SlvAMI_OFS  (2)
#define Mbufl_OFS   (0)

#define TXBI    (1 << TXBI_OFS)
#define RCBI    (1 << RCBI_OFS)
#define SlvBMI  (1 << SlvBMI_OFS)
#define TXAI    (1 << TXAI_OFS)
#define RCAI    (1 << RCAI_OFS)
#define SlvAMI  (1 << SlvAMI_OFS)
#define Mbufl   (1 << Mbufl_OFS)

#define ETXBI_OFS   (7)
#define ERCBI_OFS   (6)
#define ESlvB_OFS   (5)
#define ETXAI_OFS   (4)
#define ERCAI_OFS   (3)
#define ESlvA_OFS   (2)
#define E_OFS       (1)
#define EMbuf_OFS   (0)

#define ETXBI   (1 << ETXBI_OFS)
#define ERCBI   (1 << ERCBI_OFS)
#define ESlvB   (1 << ESlvB_OFS)
#define ETXAI   (1 << ETXAI_OFS)
#define ERCAI   (1 << ERCAI_OFS)
#define ESlvA   (1 << ESlvA_OFS)
#define E       (1 << E_OFS)
#define EMbuf   (1 << EMbuf_OFS)

#define ENSlv_OFS   (7)
#define ENSlv       (1 << ENSlv_OFS)

#define ENADC_OFS (7)
#define SADC3_OFS (3)
#define SADC2_OFS (2)
#define SADC1_OFS (1)
#define SADC0_OFS (0)

#define ENADC (1 << ENADC_OFS)
#define SADC3 (1 << SADC3_OFS)
#define SADC2 (1 << SADC2_OFS)
#define SADC1 (1 << SADC1_OFS)
#define SADC0 (1 << SADC0_OFS)

#define WDEN_OFS    (7)   
#define WDCLR_OFS   (6)  
#define WDT2_OFS    (2)   
#define WDT1_OFS    (1)   
#define WDT0_OFS    (0)   

#define WDEN    (1 << WDEN_OFS)   /** Watchdog enable (WEN in datasheet) */
#define WDCLR   (1 << WDCLR_OFS)  /** Watchdog clear (WCLR in datasheet) */
#define WDT2    (1 << WDT2_OFS)   /** Watchdog timer value, bit 2 */
#define WDT1    (1 << WDT1_OFS)   /** Watchdog timer value, bit 1 */
#define WDT0    (1 << WDT0_OFS)   /** Watchdog timer value, bit 0 */

/* Bits in the OSDRA register */
#define A1_OFS (7)
#define A0_OFS (6)
#define R3_OFS (3)
#define R2_OFS (2)
#define R1_OFS (1)
#define R0_OFS (0)

#define A1 (1 << A1_OFS)
#define A0 (1 << A0_OFS)
#define R3 (1 << R3_OFS)
#define R2 (1 << R2_OFS)
#define R1 (1 << R1_OFS)
#define R0 (1 << R0_OFS)


/* Offsets not defined because they follow natural order */
#define C4 (1 << 4)
#define C3 (1 << 3)
#define C2 (1 << 2)
#define C1 (1 << 1)
#define C0 (1 << 0)

/* Offsets not defined because they follow natural order */
#define D7 (1 << 7)
#define D6 (1 << 6)
#define D5 (1 << 5)
#define D4 (1 << 4)
#define D3 (1 << 3)
#define D2 (1 << 2)
#define D1 (1 << 1)
#define D0 (1 << 0)

#define OSDRSA_OFS  (4)
#define OSDREA_OFS  (0)
#define OSDCSA_OFS  (3)
#define OSDCEA_OFS  (3)

#define OSDRSA      (1 << OSDRSA_OFS) /* Row start address */
#define OSDREA      (1 << OSDREA_OFS) /* Row end address */
#define OSDCSA      (1 << OSDCSA_OFS) /* Column start address */
#define OSDCEA      (1 << OSDCEA_OFS) /* Column end address */

#define WEN_OFS     (2)
#define WINT_OFS    (1)
#define WSHD_OFS    (0)

#define WEN     (1 << WEN_OFS)
#define WINT    (1 << WINT_OFS)
#define WSHD    (1 << WSHD_OFS)


#define OSDEN_OFS   (7)
#define BSEN_OFS    (6)
#define SHADOW_OFS  (5)
#define FBEN_OFS    (4)
#define BLEND_OFS   (3)
#define WENclr_OFS  (2)
#define RAMclr_OFS  (1)
#define FBKGC_OFS   (0)

#define OSDEN   (1 << OSDEN_OFS)
#define BSEN    (1 << BSEN_OFS)
#define SHADOW  (1 << SHADOW_OFS)
#define FBEN    (1 << FBEN_OFS)
#define BLEND   (1 << BLEND_OFS)
#define WENclr  (1 << WENclr_OFS)
#define RAMclr  (1 << RAMclr_OFS)
#define FBKGC   (1 << FBKGC_OFS)

#define DWE_OFS (4)
#define HSP_OFS (3)
#define VSP_OFS (2)

#define DWE (1 << DWE_OFS)
#define HSP (1 << HSP_OFS)
#define VSP (1 << VSP_OFS)

#define CSR_OFS (2)
#define CSG_OFS (1)
#define CSB_OFS (0)

#define CSR (1 << CSR_OFS)
#define CSG (1 << CSG_OFS)
#define CSB (1 << CSB_OFS)

#define FSW_OFS (7)
#define FSR_OFS (2)
#define FSG_OFS (1)
#define FSB_OFS (0)

#define FSW (1 << FSW_OFS)
#define FSR (1 << FSR_OFS)
#define FSG (1 << FSG_OFS)
#define FSB (1 << FSB_OFS)

#define WW41_OFS (7)
#define WW40_OFS (6)
#define WW31_OFS (5)
#define WW30_OFS (4)
#define WW21_OFS (3)
#define WW20_OFS (2)
#define WW11_OFS (1)
#define WW10_OFS (0)

#define WW41 (1 << WW41_OFS)
#define WW40 (1 << WW40_OFS)
#define WW31 (1 << WW31_OFS)
#define WW30 (1 << WW30_OFS)
#define WW21 (1 << WW21_OFS)
#define WW20 (1 << WW20_OFS)
#define WW11 (1 << WW11_OFS)
#define WW10 (1 << WW10_OFS)

#define WH41_OFS (7)
#define WH40_OFS (6)
#define WH31_OFS (5)
#define WH30_OFS (4)
#define WH21_OFS (3)
#define WH20_OFS (2)
#define WH11_OFS (1)
#define WH10_OFS (0)

#define WH41 (1 << WH41_OFS)
#define WH40 (1 << WH40_OFS)
#define WH31 (1 << WH31_OFS)
#define WH30 (1 << WH30_OFS)
#define WH21 (1 << WH21_OFS)
#define WH20 (1 << WH20_OFS)
#define WH11 (1 << WH11_OFS)
#define WH10 (1 << WH10_OFS)


#define R1_OFS (6)
#define G1_OFS (5)
#define B1_OFS (4)
#define R2_OFS (2)
#define G2_OFS (1)
#define B2_OFS (0)

#define R1 (1 << R1_OFS)
#define G1 (1 << G1_OFS)
#define B1 (1 << B1_OFS)
#define R2 (1 << R2_OFS)
#define G2 (1 << G2_OFS)
#define B2 (1 << B2_OFS)

#define R3_OFS (6)
#define G3_OFS (5)
#define R4_OFS (2)
#define G4_OFS (1)
#define B4_OFS (0)

#define R3 (1 << R3_OFS)
#define G3 (1 << G3_OFS)
#define R4 (1 << R4_OFS)
#define G4 (1 << G4_OFS)
#define B4 (1 << B4_OFS)

#define D2_OFS (2)
#define D1_OFS (1)
#define D0_OFS (0)

#define D2 (1 << D2_OFS)
#define D1 (1 << D1_OFS)
#define D0 (1 << D0_OFS)
